# Site
title:              Agustín Covarrubias
bio:                'Intento de programador. Algo de seguridad informática'
description:        "Mi blog, y página web."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo3.png'
background:         'assets/img/placeholder-big.jpg'
<<<<<<< HEAD
locale:             es_ES
url:                https://agucova.github.io
=======
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://taylantatli.me/Moon
>>>>>>> 5ea371d96ae96a8c250cf97b08e233d9fe3997a9

# Jekyll
enforce_ssl:        agucova.github.io
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   agucova

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
<<<<<<< HEAD
email:              agucova@gmail.com
twitter:            agucova
github:             agucova
stackoverflow:      4595150/forgotten-player-agucova
#linkedin:           username
#xing:              username
instagram:          agustin_covarrubias
# lastfm:             agucova
#tumblr:             username
=======
#email:
twitter:            username
facebook:           username
github:             username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          username
#lastfm:            username
#tumblr:            username
>>>>>>> 5ea371d96ae96a8c250cf97b08e233d9fe3997a9
#pinterest:         username
#foursquare:        username
steam:              agucova
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
analytics :
  provider : google
  google :
      tracking_id : 'UA-50420608-6'
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
