# Site
title:              和光同尘
bio:                'Minimal, one column jekyll theme.'
description:        "lypeer|和其光，同其尘"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
locale:             en_US
url:                "http://lypeer"

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            lypeer
facebook:           lypeer
github:             lypeer
#stackoverflow:      123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:           username
#xing:              username
instagram:          lypeer
#lastfm:             username
#tumblr:             username
#pinterest:         username
#foursquare:        username
steam:              lypeer
#dribbble:          username
#youtube:            username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
