# Site
title:              Kopi
bio:                'Coffee delivered daily.'
description:        "Kopi is a monthly subscription service which delivers freshly prepared coffee in tumblers on a daily basis."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://kopi.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   Kopi

# Social
# if you don't have any of social below, comment the line.
google:
  plus:             100188583768021555737
  analytics:        UA-100326922-1 
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              contact@kopi.cafe
twitter:            kopimtl
facebook:           kopimtl
github-url:         https://github.com/Kopi/
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           kopi.mtl
#xing:              username
instagram:          kopimtl
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
